### ISSUE TITLE
Regular Expression Denial of Service

### ISSUE THREAD

**Issue by cleiton-tavares** [Moesif/moesif-express#4]
As reported by nodesecurity there is a known bug that allows denial of service as attached below

NodeSecurity Report
Affected versions of string are vulnerable to regular expression denial of service when specifically crafted untrusted user input is passed into the underscore or unescapeHTML methods.

Read more - https://nodesecurity.io/advisories/536

**Comment by xinghengwang** [comment]
Thank you. 

The issue is regarding using _underscore_ and _unescapeHTML_ methods of the __string.js__ libary. 
https://github.com/jprichardson/string.js/issues/212

The moesif-express library does not use those two methods, but regardless, we will also remove the dependency on "string.js" sometime in the future.
